Fix storage exception
AY2021S1-CS2113T-T12-3/tp pull request #195
Opened 2020-11-03 07:33 UTC by NeilBaner

Fix for #177 .

2020-11-03 11:01 UTC, yAOwzers commented on docs/_config.yml
> +theme: jekyll-theme-hacker
HAHA DID YOU JUST CHANGE THE THEME BACK

2020-11-03 11:21 UTC, NeilBaner commented
Not intentionally probably committed the copy on my machine which hadn't been updated lol. Oops. Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: J Neo <notifications@github.com> Date: 3/11/20  19:01  (GMT+08:00) To: AY2021S1-CS2113T-T12-3/tp <tp@noreply.github.com> Cc: Neil Banerjee <neilb5400@gmail.com>, Author <author@noreply.github.com> Subject: Re: [AY2021S1-CS2113T-T12-3/tp] Fix storage exception (#195) 
@yAOwzers commented on this pull request.



In docs/_config.yml:
> @@ -1,3 +1,3 @@
-theme: jekyll-theme-cayman
+theme: jekyll-theme-hacker

HAHA DID YOU JUST CHANGE THE THEME BACK

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-11-03 16:06 UTC, chuckiex3 requested changes
please change the theme back to cayman, thank you HAHAHA

2020-11-04 01:33 UTC, NeilBaner commented
> 
> 
> please change the theme back to cayman, thank you HAHAHA

Done.

2020-11-04 02:20 UTC, chuckiex3 approved these changes

2020-11-04 03:29 UTC, yAOwzers approved these changes
NOICE

2020-11-04 03:29 UTC, merged